name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/chekcout@v3
        - name: exportGame
          uses: firebelley:godot-export@5.2.1
          with: 
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_linux.x86_64.zip
            godot_export_templates_download_url:  https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_export_templates.tpz
            relative_project_path: ./
            create_release: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
